mysql:
  #image: jsurf/rpi-mariadb
  build: ./mysql
  container_name: rpi3-mariadb10
  restart: unless-stopped
  ports:
    - "3306:3306"
  volumes:
    - "/var/lib/docker-volume/mysql:/var/lib/mysql"
#    - "./mysql/init-sql:/docker-entrypoint-initdb.d"
  environment:
#    - "MYSQL_USER=lhysin"
#    - "MYSQL_PASSWORD=lhysin"
    - "MYSQL_ROOT_PASSWORD=root"

#redis:
#  #image: arm32v7/redis
#  build: ./redis
#  container_name: rpi3-redis
#  restart: unless-stopped
#  command: redis-server --appendonly yes --maxmemory 256mb --tcp-backlog 128 --requirepass lhysin
#  ports:
#    - "6379:6379"
#  volumes:
#    - "/var/lib/docker-volume/redis/data:/data"

#mongodb:
#  build: ./mongodb
#  container_name: rpi3-mongodb3
#  restart: unless-stopped
#  command: mongod --auth
#  ports:
#    - "27017:27017"
#  volumes:
#    - "/var/lib/docker-volume/mongodb/data/db:/data/db"
#    - "/var/lib/docker-volume/mongodb/data/configdb:/data/configdb"
